# Generated by Django 6.0.7 on 2026-08-11 09:13

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.UUIDField()),
                ('file', cloudinary.models.CloudinaryField(max_length=255, verbose_name='media')),
                ('role', models.CharField(choices=[('avatar', 'Avatar'), ('cover', 'Cover'), ('logo', 'Logo'), ('gallery', 'Gallery'), ('attachment', 'Attachment')], max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='TestMedia',
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='media_media_content_c23fc6_idx'),
        ),
    ]
