# Generated by Django 6.0.7 on 2026-08-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_delete_testmedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='role',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('cover', 'Cover'), ('banner', 'Banner'), ('logo', 'Logo'), ('gallery', 'Gallery'), ('attachment', 'Attachment')], max_length=20),
        ),
    ]
