# Generated by Django 6.0.7 on 2026-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_media_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='role',
            field=models.CharField(choices=[('avatar', 'Avatar'), ('cover', 'Cover'), ('banner', 'Banner'), ('logo', 'Logo'), ('gallery', 'Gallery'), ('attachment', 'Attachment'), ('other', 'Other')], max_length=20),
        ),
    ]
