# Generated by Django 6.0.7 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_media_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='original_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='media',
            name='role',
            field=models.CharField(choices=[('post', 'Post'), ('avatar', 'Avatar'), ('cover', 'Cover'), ('banner', 'Banner'), ('logo', 'Logo'), ('gallery', 'Gallery'), ('attachment', 'Attachment'), ('other', 'Other')], max_length=20),
        ),
    ]
