
@baseUrl = http://127.0.0.1:8000/api/v1/accounts/auth/
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NzQ3ODI5LCJpYXQiOjE3ODQ3NDQyMjksImp0aSI6ImVhYWY1ZmRiZTM2OTQ3ZjViMmViOGNlNTcxYzg2ZGRiIiwidXNlcl9pZCI6ImU4ZjU5ZjM1LWEzZmItNGQxNy04YmMxLTNmZGI3MjZjNmI2YSJ9.hhf1Zg29fO_NxRPJkM6Ek5Erai_e6jl4ReIUY5yo77I
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NzMzNjIyOSwiaWF0IjoxNzg0NzQ0MjI5LCJqdGkiOiI0OTliZThhMWI3OGM0ZjYwOWQzZTYxYzJkMWY3Nzg4YyIsInVzZXJfaWQiOiJlOGY1OWYzNS1hM2ZiLTRkMTctOGJjMS0zZmRiNzI2YzZiNmEifQ.M5nGUZIk1s_NlYdhZpeYf7FUyw2Rv8xHgi8H5Jux5jM
@clubId = 9af7488b-98e3-4a93-a617-c35dc19a579d
@postId = 7391907467086532608
@eventId = 7392190347431907328
@userId = 3


###
GET {{baseUrl}}users/ HTTP/1.1
Authorization: Bearer {{accessToken}}


###
POST {{baseUrl}}jwt/logout/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}



{
  "refresh": "{{refreshToken}}"
}





###
POST {{baseUrl}}login/ HTTP/1.1
Content-Type: application/json

{
    "username_or_email" : "anotheruser",
    "password" : "another@12345"
}


###
POST {{baseUrl}}jwt/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "{{refreshToken}}"
}

###
POST {{baseUrl}}jwt/verify/ HTTP/1.1
Content-Type: application/json

{
    "token" : "{{accessToken}}"
}


###
POST {{baseUrl}}register/ HTTP/1.1
Content-Type: application/json

{
    "username" : "anotheruser",
    "email" : "anotheruser@gmail.com",
    "password" : "another@12345",
    "re_password" : "another@12345"
}
###
GET {{baseUrl}}users/user/prottoy/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}




# POSTS
###
GET {{baseUrl}}clubs/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}


###
GET {{baseUrl}}clubs/{{clubId}}/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}



###
GET {{baseUrl}}clubs/{{clubId}}/members/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
