# Generated by Django 6.0.7 on 2026-08-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_alter_email_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='type',
            field=models.CharField(choices=[('system', 'SYSTEM'), ('club', 'CLUB'), ('other', 'Other')], default='club', max_length=32),
        ),
    ]
