# Generated by Django 6.0.7 on 2026-07-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clubpost',
            name='clubs_clubp_club_id_1b722a_idx',
        ),
        migrations.DeleteModel(
            name='ClubPost',
        ),
    ]
