# Generated by Django 6.0.7 on 2026-07-20 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_remove_clubpost_clubs_clubp_club_id_1b722a_idx_and_more'),
        ('institutes', '0005_instituteaffiliate_academicprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('icon', models.ImageField(upload_to='clubs/images/category_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Application',
                'verbose_name_plural': 'Membership Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplicationForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Membership Application Form',
                'verbose_name_plural': 'Membership Application Forms',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplicationResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='club',
            name='clubs_club_privacy_6d416f_idx',
        ),
        migrations.AddField(
            model_name='club',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='join_mode',
            field=models.CharField(choices=[('instant', 'Instant'), ('application', 'Application Required'), ('invite_only', 'Invite Only')], default='instant', help_text='How users join. Constrained by `privacy` — see clean().', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('exclusive', 'Exclusive'), ('cross_institute', 'Cross Institute')], default='global', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='club',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('secret', 'Secret')], default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='clubs.category'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['owner'], name='clubs_club_owner_i_35a16f_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['privacy', 'status'], name='clubs_club_privacy_f5b782_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['scope', 'status'], name='clubs_club_scope_9c3f07_idx'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership', to='clubs.membershipapplication'),
        ),
        migrations.AddField(
            model_name='membershipapplicationform',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='clubs.club'),
        ),
        migrations.AddField(
            model_name='membershipapplicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clubs.membershipapplication'),
        ),
        migrations.AddField(
            model_name='membershipapplicationresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clubs.membershipapplicationform'),
        ),
        migrations.RemoveField(
            model_name='club',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='club',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='club',
            name='is_visible',
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['club', 'status'], name='clubs_membe_club_id_ae319a_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('club', 'applicant'), name='unique_pending_application_per_club'),
        ),
        migrations.AddIndex(
            model_name='membershipapplicationform',
            index=models.Index(fields=['club', 'order'], name='clubs_membe_club_id_03e4a7_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplicationresponse',
            index=models.Index(fields=['application'], name='clubs_membe_applica_689d29_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipapplicationresponse',
            constraint=models.UniqueConstraint(fields=('application', 'question'), name='unique_answer_per_question'),
        ),
    ]
