# Generated by Django 6.0.7 on 2026-07-21 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_rename_application_enabled_club_enable_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='enable_applications',
        ),
    ]
