# Generated by Django 6.0.7 on 2026-07-22 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_remove_club_enable_applications'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('email', 'Email'), ('url', 'URL'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=30)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='membershipapplicationform',
            name='clubs_membe_club_id_03e4a7_idx',
        ),
        migrations.AddField(
            model_name='form',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='form',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_forms', to='clubs.form'),
        ),
        migrations.AddField(
            model_name='formquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='clubs.form'),
        ),
        migrations.AlterField(
            model_name='membershipapplicationresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clubs.formquestion'),
        ),
        migrations.RemoveField(
            model_name='membershipapplicationform',
            name='club',
        ),
        migrations.AddIndex(
            model_name='form',
            index=models.Index(fields=['content_type', 'object_id'], name='clubs_form_content_488b77_idx'),
        ),
        migrations.AddConstraint(
            model_name='form',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('content_type', 'object_id'), name='unique_active_form_per_owner'),
        ),
        migrations.AddIndex(
            model_name='formquestion',
            index=models.Index(fields=['form', 'order'], name='clubs_formq_form_id_40c569_idx'),
        ),
        migrations.DeleteModel(
            name='MembershipApplicationForm',
        ),
    ]
