# Generated by Django 6.0.7 on 2026-07-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_form_formquestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='message',
            field=models.TextField(blank=True, help_text='Optional note from the applicant, especially useful when the club has no form.', null=True),
        ),
    ]
