# Generated by Django 6.0.7 on 2026-07-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_alter_club_origin'),
        ('institutes', '0005_instituteaffiliate_academicprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='origin',
            field=models.ForeignKey(blank=True, help_text='Null means local / global / cross-institute club', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='institutes.institute'),
        ),
    ]
