# Generated by Django 6.0.7 on 2026-08-18 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_club_paused_at_membership_left_at_alter_club_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clubs.club')),
                ('head', models.OneToOneField(blank=True, help_text='The member who heads this department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='clubs.membership')),
            ],
            options={
                'db_table': 'club_departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='clubs.clubdepartment')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='clubs.membership')),
            ],
            options={
                'db_table': 'membership_departments',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='members', through='clubs.MembershipDepartment', to='clubs.clubdepartment'),
        ),
        migrations.AddConstraint(
            model_name='clubdepartment',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_department_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='membershipdepartment',
            constraint=models.UniqueConstraint(fields=('membership', 'department'), name='unique_member_department'),
        ),
    ]
