# Generated by Django 6.0.7 on 2026-08-18 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_clubdepartment_membershipdepartment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'department_templates',
            },
        ),
    ]
