# Generated by Django 6.0.7 on 2026-08-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_departmenttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_decision', models.CharField(choices=[('manual', 'Manual Review'), ('auto_accept', 'Auto Accept')], default='manual', max_length=20)),
                ('allow_reapplication', models.BooleanField(default=True)),
                ('leave_application', models.BooleanField(default=True)),
                ('notify_on_new_member', models.BooleanField(default=True)),
                ('notify_on_new_application', models.BooleanField(default=True)),
                ('notify_on_event_reminder', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='clubs.club')),
            ],
            options={
                'verbose_name': 'Club Preference',
                'verbose_name_plural': 'Club Preferences',
                'db_table': 'club_preferences',
            },
        ),
    ]
