# Generated by Django 6.0.7 on 2026-08-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_clubpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubpreference',
            name='leave_application',
            field=models.BooleanField(default=False),
        ),
    ]
