# Generated by Django 6.0.7 on 2026-09-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_clubpreference_leave_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubpreference',
            name='allow_public_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clubpreference',
            name='requires_interview',
            field=models.BooleanField(default=False),
        ),
    ]
