# Generated by Django 6.0.7 on 2026-09-30 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_clubpreference_allow_public_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipapplicationresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clubs.membershipapplication'),
        ),
    ]
