# Generated by Django 6.0.7 on 2026-10-01 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_alter_membershipapplicationresponse_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Answer',
                'verbose_name_plural': 'Form Answers',
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='membershipapplicationresponse',
            name='clubs_membe_applica_689d29_idx',
        ),
        migrations.RemoveConstraint(
            model_name='membershipapplicationresponse',
            name='unique_answer_per_question',
        ),
        migrations.AddField(
            model_name='formanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clubs.formquestion'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='clubs.form'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='respondent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='clubs.formsubmission'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='submission',
            field=models.OneToOneField(blank=True, help_text='Filled-in questionnaire when the club requires one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_application', to='clubs.formsubmission'),
        ),
        migrations.RemoveField(
            model_name='membershipapplicationresponse',
            name='application',
        ),
        migrations.RemoveField(
            model_name='membershipapplicationresponse',
            name='question',
        ),
        migrations.AddIndex(
            model_name='formsubmission',
            index=models.Index(fields=['form', 'respondent'], name='clubs_forms_form_id_6a6a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='formanswer',
            index=models.Index(fields=['submission'], name='clubs_forma_submiss_65570b_idx'),
        ),
        migrations.AddConstraint(
            model_name='formanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_answer_per_question_per_submission'),
        ),
        migrations.DeleteModel(
            name='MembershipApplicationResponse',
        ),
    ]
