// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/@/auth/sign-up": {
    params: {};
  };
  "/@/auth/sign-in": {
    params: {};
  };
  "/@/u/:username": {
    params: {
      "username": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/@/auth/sign-up" | "/@/auth/sign-in" | "/@/u/:username";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/public/auth/sign-up.route.tsx": {
    id: "routes/public/auth/sign-up.route";
    page: "/@/auth/sign-up";
  };
  "./routes/public/auth/sign-in.tsx": {
    id: "routes/public/auth/sign-in";
    page: "/@/auth/sign-in";
  };
  "./routes/public/user/profile.tsx": {
    id: "routes/public/user/profile";
    page: "/@/u/:username";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/public/auth/sign-up.route": typeof import("./app/./routes/public/auth/sign-up.route.tsx");
  "routes/public/auth/sign-in": typeof import("./app/./routes/public/auth/sign-in.tsx");
  "routes/public/user/profile": typeof import("./app/./routes/public/user/profile.tsx");
};