export const settingsRoutes = {
  base: "/@/settings/",
  account: {
    base: "/@/settings/account/",
    password: "/@/settings/account/password/",
    email: "/@/settings/account/email/",
    notifications: "/@/settings/account/notifications/",
    profile: "/@/settings/account/profile/",
    security: "/@/settings/account/security/",
    privacy: "/@/settings/account/privacy/",
    general: "/@/settings/account/general/",
    apps: "/@/settings/account/apps/",
    shortcuts: "/@/settings/account/shortcuts/",
    accessibility: "/@/settings/account/accessibility/",
    appearance: "/@/settings/account/appearance/",
    sounds: "/@/settings/account/sounds/",
    language: "/@/settings/account/language/",
    region: "/@/settings/account/region/",
    time: "/@/settings/account/time/",
    date: "/@/settings/account/date/",
    timezone: "/@/settings/account/timezone/",
    theme: "/@/settings/account/theme/",
  },
  affiliations: "/@/settings/affiliations/",
  privacy: "/@/settings/privacy/",
} as const;
