# Generated by Django 6.0.7 on 2026-07-19 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['-created_at'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='instituteemaildomain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email Domain', 'verbose_name_plural': 'Email Domains'},
        ),
        migrations.AddField(
            model_name='instituteemaildomain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instituteemaildomain',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteemaildomain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='instituteemaildomain',
            table='institute_email_domains',
        ),
    ]
