# Generated by Django 6.0.7 on 2026-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_institute_institute_name_b3ac45_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituteemaildomain',
            name='domain_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('alumni', 'Alumni')], default='student', max_length=20),
        ),
    ]
