# Generated by Django 6.0.7 on 2026-07-19 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0004_alter_instituteemaildomain_domain_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteAffiliate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliates', to='institutes.institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_affiliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institute Affiliate',
                'verbose_name_plural': 'Institute Affiliates',
                'db_table': 'institute_affiliates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('batch', models.PositiveIntegerField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('joined_institute_at', models.DateField(blank=True, null=True)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='institutes.department')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_profile', to='institutes.instituteaffiliate')),
            ],
            options={
                'verbose_name': 'Academic Profile',
                'verbose_name_plural': 'Academic Profiles',
                'db_table': 'academic_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='instituteaffiliate',
            constraint=models.UniqueConstraint(fields=('institute', 'user'), name='unique_institute_affiliation'),
        ),
        migrations.AddIndex(
            model_name='academicprofile',
            index=models.Index(fields=['member'], name='academic_pr_member__89648d_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprofile',
            index=models.Index(fields=['academic_email'], name='academic_pr_academi_2660df_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprofile',
            index=models.Index(fields=['department'], name='academic_pr_departm_1fad52_idx'),
        ),
        migrations.AddIndex(
            model_name='academicprofile',
            index=models.Index(fields=['student_id'], name='academic_pr_student_00cf03_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicprofile',
            constraint=models.UniqueConstraint(fields=('member',), name='unique_academic_profile'),
        ),
        migrations.AlterUniqueTogether(
            name='academicprofile',
            unique_together={('member', 'academic_email')},
        ),
    ]
