# Generated by Django 6.0.7 on 2026-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='object_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='share',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
