# Generated by Django 6.0.7 on 2026-07-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['name', 'code'], name='institute_name_b3ac45_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['country'], name='institute_country_37281f_idx'),
        ),
    ]
