# Generated by Django 6.0.7 on 2026-08-16 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0006_alter_instituteaffiliate_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteaffiliate',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_affiliations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='verification_method',
            field=models.CharField(choices=[('email', 'Email Confirmation'), ('manual', 'Manual Review')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
