# Generated by Django 6.0.7 on 2026-08-16 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0007_instituteaffiliate_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteaffiliate',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instituteaffiliate',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
