# Generated by Django 6.0.7 on 2026-08-16 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0008_instituteaffiliate_token_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='institutes.department'),
        ),
    ]
