# Generated by Django 6.0.7 on 2026-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_category_membershipapplication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='application_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
