# Generated by Django 6.0.7 on 2026-07-20 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_application_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='application_enabled',
            new_name='enable_applications',
        ),
    ]
