# Generated by Django 6.0.7 on 2026-09-21 08:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0020_clubpreference_allow_public_posts_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group'), ('CLUB', 'Club')], default='DIRECT', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='clubs.club')),
            ],
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left'), ('blocked', 'Blocked'), ('removed', 'Removed')], default='joined', max_length=10)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('muted_until', models.DateTimeField(blank=True, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='realtime.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('client_msg_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('msg_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('VOICE', 'Voice'), ('STICKER', 'Sticker'), ('SYSTEM', 'System event'), ('LOCATION', 'Location')], default='TEXT', max_length=16)),
                ('is_pinned', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_mode', models.CharField(choices=[('NONE', 'Not deleted'), ('FOR_ME', 'Deleted for me'), ('FOR_EVERYONE', 'Deleted for everyone')], default='NONE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='realtime.chat')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='realtime.message')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='realtime.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_requests', to='realtime.chat')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('seen', 'Seen')], default='sent', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='realtime.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for', to='realtime.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['club'], name='realtime_ch_club_id_8b1809_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', 'created_at'], name='realtime_ch_type_8c79de_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message_at'], name='realtime_ch_last_me_ca38b3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'status'], name='realtime_ch_user_id_759243_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat', 'status'], name='realtime_ch_chat_id_37b83f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'is_pinned', '-joined_at'], name='realtime_ch_user_id_588000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='realtime_me_chat_id_bd6ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='realtime_me_sender__3a4c15_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='realtime_me_message_9286d5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', 'created_at'], name='realtime_me_user_id_8e33bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['to_user', 'status', '-created_at'], name='realtime_me_to_user_f6fb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['from_user', 'status', '-created_at'], name='realtime_me_from_us_d0e8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='realtime_me_user_id_b6dfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'status'], name='realtime_me_message_c84af3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagestatus',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='usermessagehidden',
            index=models.Index(fields=['user', 'message'], name='realtime_us_user_id_c52e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermessagehidden',
            unique_together={('user', 'message')},
        ),
    ]
