# Generated by Django 5.2.17 on 2026-09-20 23:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_clubpreference_allow_public_posts_and_more'),
        ('realtime', '0002_chat_is_pinned_chat_updated_at_message_is_pinned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='file', max_length=16)),
                ('file_url', models.URLField(max_length=500)),
                ('thumb_url', models.URLField(blank=True, max_length=500, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessageHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.AddField(
            model_name='chat',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='client_msg_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_mode',
            field=models.CharField(choices=[('NONE', 'Not deleted'), ('FOR_ME', 'Deleted for me'), ('FOR_EVERYONE', 'Deleted for everyone')], default='NONE', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('FILE', 'File'), ('VOICE', 'Voice'), ('STICKER', 'Sticker'), ('SYSTEM', 'System event'), ('LOCATION', 'Location')], default='TEXT', max_length=16),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagestatus',
            name='seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='messagestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_receipts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['club'], name='realtime_ch_club_id_8b1809_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', 'created_at'], name='realtime_ch_type_8c79de_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['last_message_at'], name='realtime_ch_last_me_ca38b3_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'status'], name='realtime_ch_user_id_759243_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat', 'status'], name='realtime_ch_chat_id_37b83f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'is_pinned', '-joined_at'], name='realtime_ch_user_id_588000_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='realtime_me_chat_id_bd6ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='realtime_me_sender__3a4c15_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['message', 'emoji'], name='realtime_me_message_9286d5_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereaction',
            index=models.Index(fields=['user', 'created_at'], name='realtime_me_user_id_8e33bf_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['user', 'status'], name='realtime_me_user_id_b6dfb8_idx'),
        ),
        migrations.AddIndex(
            model_name='messagestatus',
            index=models.Index(fields=['message', 'status'], name='realtime_me_message_c84af3_idx'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='realtime.message'),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagerequest',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usermessagehidden',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_for', to='realtime.message'),
        ),
        migrations.AddField(
            model_name='usermessagehidden',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messageattachment',
            index=models.Index(fields=['message', 'created_at'], name='realtime_me_message_520299_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['to_user', 'status', '-created_at'], name='realtime_me_to_user_f6fb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='messagerequest',
            index=models.Index(fields=['from_user', 'status', '-created_at'], name='realtime_me_from_us_d0e8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='usermessagehidden',
            index=models.Index(fields=['user', 'message'], name='realtime_us_user_id_c52e0b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usermessagehidden',
            unique_together={('user', 'message')},
        ),
    ]
