# Generated by Django 5.2.17 on 2026-09-20 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_original_file_name_alter_media_role'),
        ('realtime', '0003_messageattachment_messagerequest_usermessagehidden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_attachments', to='media.media'),
        ),
    ]
