# Generated by Django 5.2.17 on 2026-09-21 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0004_messageattachment_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerequest',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_requests', to='realtime.chat'),
        ),
    ]
