# Generated by Django 6.0.7 on 2026-09-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtarget',
            name='object_id',
            field=models.UUIDField(),
        ),
    ]
