# Generated by Django 6.0.7 on 2026-08-31 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_alter_clubpreference_leave_application'),
        ('posts', '0002_post_deleted_at_post_edited_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_is_dele_876c95_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['deleted_at'], name='posts_post_deleted_b51458_idx'),
        ),
    ]
